#ifndef TOPICS_H__
#define TOPICS_H__

enum class Topics {
	Array,
	String,
	Hash_Table,
	Dynamic_Programming,
	Math,
	Sorting,
	Greedy,
	Depth_First_Search,
	Database,
	Binary_Search,
	Matrix,
	Tree,
	Breadth_First_Search,
	Bit_Manipulation,
	Two_Pointers,
	Binary_Tree,
	Heap_Priority_Queue,
	Prefix_Sum,
	Simulation,
	Stack,
	Graph,
	Counting,
	Sliding_Window,
	Design,
	Backtracking,
	Enumeration,
	Union_Find,
	Linked_List,
	Ordered_Set,
	Monotonic_Stack,
	Number_Theory,
	Trie,
	Segment_Tree,
	Bitmask,
	Divide_and_Conquer,
	Queue,
	Recursion,
	Binary_Search_Tree,
	Combinatorics,
	Binary_Indexed_Tree,
	Geometry,
	Memoization,
	Hash_Function,
	Topological_Sort,
	String_Matching,
	Shortest_Path,
	Game_Theory,
	Rolling_Hash,
	Interactive,
	Data_Stream,
	Brainteaser,
	Monotonic_Queue,
	Randomized,
	Merge_Sort,
	Doubly_Linked_List,
	Iterator,
	Concurrency,
	Probability_and_Statistics,
	Counting_Sort,
	Quickselect,
	Suffix_Array,
	Bucket_Sort,
	Minimum_Spanning_Tree,
	Shell,
	Line_Sweep,
	Reservoir_Sampling,
	Strongly_Connected_Component,
	Eulerian_Circuit,
	Radix_Sort,
	Rejection_Sampling,
	Biconnected_Component
};

#endif // !TOPICS_H__


